Get rid of unused result error
In Assignment 6, I get the error
```
aesdsocket.c:59:9: error: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Werror=unused-result]
   59 |         write(fd, "timestamp:", 10);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
aesdsocket.c:60:9: error: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Werror=unused-result]
   60 |         write(fd, buf, strlen(buf));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
aesdsocket.c:61:9: error: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Werror=unused-result]
   61 |         write(fd, "\n", 1);
      |         ^~~~~~~~~~~~~~~~~~
aesdsocket.c: In function 'thread_func':
aesdsocket.c:287:9: error: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Werror=unused-result]
  287 |         write(fd, buf, strlen(buf)); // ignore failure to write
```

This commit gets rid of it